#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd

import warnings
warnings.simplefilter(action='ignore')


# In[ ]:


import timeit


# In[12]:


import csv   


# In[2]:


from tsfresh import extract_features, extract_relevant_features, select_features
from tsfresh.utilities.dataframe_functions import impute
from tsfresh.feature_extraction import ComprehensiveFCParameters


# In[3]:


CO_processed_path = '/home/ubuntu/workspace_rohan/project/data/raw/CO_processed.csv'
CO_timeseries_path = '/home/ubuntu/workspace_rohan/project/data/raw/CO_timeseries.csv'


# In[4]:


data = pd.read_csv(CO_processed_path)
data = data.drop(["Unnamed: 0"],axis=1)


# In[5]:


data_tseries = pd.read_csv(CO_timeseries_path)
data_tseries = data_tseries.drop(["Unnamed: 0"],axis=1)


# In[6]:


data_tseries = pd.merge(data_tseries, data, how='left', left_on=['fecha_de_visita', 'codigo_de_cliente', 'codigo_de_producto'], right_on=['fecha_de_visita', 'codigo_de_cliente', 'codigo_de_producto'])


# In[7]:


data_tseries = data_tseries.dropna()


# In[ ]:





# In[67]:


ts_cols = ['visit_count__variance_larger_than_standard_deviation',
 'visit_count__has_duplicate_max',
 'visit_count__has_duplicate_min',
 'visit_count__has_duplicate',
 'visit_count__sum_values',
 'visit_count__abs_energy',
 'visit_count__mean_abs_change',
 'visit_count__mean_change',
 'visit_count__mean_second_derivative_central',
 'visit_count__median',
 'visit_count__mean',
 'visit_count__length',
 'visit_count__standard_deviation',
 'visit_count__variation_coefficient',
 'visit_count__variance',
 'visit_count__skewness',
 'visit_count__kurtosis',
 'visit_count__root_mean_square',
 'visit_count__absolute_sum_of_changes',
 'visit_count__longest_strike_below_mean',
 'visit_count__longest_strike_above_mean',
 'visit_count__count_above_mean',
 'visit_count__count_below_mean',
 'visit_count__last_location_of_maximum',
 'visit_count__first_location_of_maximum',
 'visit_count__last_location_of_minimum',
 'visit_count__first_location_of_minimum',
 'visit_count__percentage_of_reoccurring_values_to_all_values',
 'visit_count__percentage_of_reoccurring_datapoints_to_all_datapoints',
 'visit_count__sum_of_reoccurring_values',
 'visit_count__sum_of_reoccurring_data_points',
 'visit_count__ratio_value_number_to_time_series_length',
 'visit_count__sample_entropy',
 'visit_count__maximum',
 'visit_count__minimum',
 'visit_count__benford_correlation',
 'visit_count__time_reversal_asymmetry_statistic__lag_1',
 'visit_count__time_reversal_asymmetry_statistic__lag_2',
 'visit_count__time_reversal_asymmetry_statistic__lag_3',
 'visit_count__c3__lag_1',
 'visit_count__c3__lag_2',
 'visit_count__c3__lag_3',
 'visit_count__cid_ce__normalize_True',
 'visit_count__cid_ce__normalize_False',
 'visit_count__symmetry_looking__r_0.0',
 'visit_count__symmetry_looking__r_0.05',
 'visit_count__symmetry_looking__r_0.1',
 'visit_count__symmetry_looking__r_0.15000000000000002',
 'visit_count__symmetry_looking__r_0.2',
 'visit_count__symmetry_looking__r_0.25',
 'visit_count__symmetry_looking__r_0.30000000000000004',
 'visit_count__symmetry_looking__r_0.35000000000000003',
 'visit_count__symmetry_looking__r_0.4',
 'visit_count__symmetry_looking__r_0.45',
 'visit_count__symmetry_looking__r_0.5',
 'visit_count__symmetry_looking__r_0.55',
 'visit_count__symmetry_looking__r_0.6000000000000001',
 'visit_count__symmetry_looking__r_0.65',
 'visit_count__symmetry_looking__r_0.7000000000000001',
 'visit_count__symmetry_looking__r_0.75',
 'visit_count__symmetry_looking__r_0.8',
 'visit_count__symmetry_looking__r_0.8500000000000001',
 'visit_count__symmetry_looking__r_0.9',
 'visit_count__symmetry_looking__r_0.9500000000000001',
 'visit_count__large_standard_deviation__r_0.05',
 'visit_count__large_standard_deviation__r_0.1',
 'visit_count__large_standard_deviation__r_0.15000000000000002',
 'visit_count__large_standard_deviation__r_0.2',
 'visit_count__large_standard_deviation__r_0.25',
 'visit_count__large_standard_deviation__r_0.30000000000000004',
 'visit_count__large_standard_deviation__r_0.35000000000000003',
 'visit_count__large_standard_deviation__r_0.4',
 'visit_count__large_standard_deviation__r_0.45',
 'visit_count__large_standard_deviation__r_0.5',
 'visit_count__large_standard_deviation__r_0.55',
 'visit_count__large_standard_deviation__r_0.6000000000000001',
 'visit_count__large_standard_deviation__r_0.65',
 'visit_count__large_standard_deviation__r_0.7000000000000001',
 'visit_count__large_standard_deviation__r_0.75',
 'visit_count__large_standard_deviation__r_0.8',
 'visit_count__large_standard_deviation__r_0.8500000000000001',
 'visit_count__large_standard_deviation__r_0.9',
 'visit_count__large_standard_deviation__r_0.9500000000000001',
 'visit_count__quantile__q_0.1',
 'visit_count__quantile__q_0.2',
 'visit_count__quantile__q_0.3',
 'visit_count__quantile__q_0.4',
 'visit_count__quantile__q_0.6',
 'visit_count__quantile__q_0.7',
 'visit_count__quantile__q_0.8',
 'visit_count__quantile__q_0.9',
 'visit_count__autocorrelation__lag_0',
 'visit_count__autocorrelation__lag_1',
 'visit_count__autocorrelation__lag_2',
 'visit_count__autocorrelation__lag_3',
 'visit_count__autocorrelation__lag_4',
 'visit_count__autocorrelation__lag_5',
 'visit_count__autocorrelation__lag_6',
 'visit_count__autocorrelation__lag_7',
 'visit_count__autocorrelation__lag_8',
 'visit_count__autocorrelation__lag_9',
 'visit_count__agg_autocorrelation__f_agg_"mean"__maxlag_40',
 'visit_count__agg_autocorrelation__f_agg_"median"__maxlag_40',
 'visit_count__agg_autocorrelation__f_agg_"var"__maxlag_40',
 'visit_count__partial_autocorrelation__lag_0',
 'visit_count__partial_autocorrelation__lag_1',
 'visit_count__partial_autocorrelation__lag_2',
 'visit_count__partial_autocorrelation__lag_3',
 'visit_count__partial_autocorrelation__lag_4',
 'visit_count__partial_autocorrelation__lag_5',
 'visit_count__partial_autocorrelation__lag_6',
 'visit_count__partial_autocorrelation__lag_7',
 'visit_count__partial_autocorrelation__lag_8',
 'visit_count__partial_autocorrelation__lag_9',
 'visit_count__number_cwt_peaks__n_1',
 'visit_count__number_cwt_peaks__n_5',
 'visit_count__number_peaks__n_1',
 'visit_count__number_peaks__n_3',
 'visit_count__number_peaks__n_5',
 'visit_count__number_peaks__n_10',
 'visit_count__number_peaks__n_50',
 'visit_count__binned_entropy__max_bins_10',
 'visit_count__index_mass_quantile__q_0.1',
 'visit_count__index_mass_quantile__q_0.2',
 'visit_count__index_mass_quantile__q_0.3',
 'visit_count__index_mass_quantile__q_0.4',
 'visit_count__index_mass_quantile__q_0.6',
 'visit_count__index_mass_quantile__q_0.7',
 'visit_count__index_mass_quantile__q_0.8',
 'visit_count__index_mass_quantile__q_0.9',
 'visit_count__cwt_coefficients__coeff_0__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_0__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_0__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_0__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_1__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_1__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_1__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_1__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_2__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_2__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_2__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_2__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_3__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_3__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_3__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_3__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_4__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_4__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_4__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_4__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_5__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_5__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_5__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_5__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_6__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_6__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_6__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_6__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_7__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_7__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_7__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_7__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_8__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_8__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_8__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_8__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_9__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_9__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_9__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_9__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_10__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_10__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_10__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_10__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_11__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_11__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_11__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_11__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_12__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_12__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_12__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_12__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_13__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_13__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_13__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_13__w_20__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_14__w_2__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_14__w_5__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_14__w_10__widths_(2, 5, 10, 20)',
 'visit_count__cwt_coefficients__coeff_14__w_20__widths_(2, 5, 10, 20)',
 'visit_count__spkt_welch_density__coeff_2',
 'visit_count__spkt_welch_density__coeff_5',
 'visit_count__spkt_welch_density__coeff_8',
 'visit_count__ar_coefficient__coeff_0__k_10',
 'visit_count__ar_coefficient__coeff_1__k_10',
 'visit_count__ar_coefficient__coeff_2__k_10',
 'visit_count__ar_coefficient__coeff_3__k_10',
 'visit_count__ar_coefficient__coeff_4__k_10',
 'visit_count__ar_coefficient__coeff_5__k_10',
 'visit_count__ar_coefficient__coeff_6__k_10',
 'visit_count__ar_coefficient__coeff_7__k_10',
 'visit_count__ar_coefficient__coeff_8__k_10',
 'visit_count__ar_coefficient__coeff_9__k_10',
 'visit_count__ar_coefficient__coeff_10__k_10',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.2__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.2__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.2__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.2__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.4__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.4__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.4__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.4__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.6__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.8__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.8__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.8__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.0',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.0',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.4__ql_0.2',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.4__ql_0.2',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.4__ql_0.2',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.4__ql_0.2',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.6__ql_0.2',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.2',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.2',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.2',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.8__ql_0.2',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.8__ql_0.2',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.8__ql_0.2',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.2',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.2',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.2',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.2',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.2',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.6__ql_0.4',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.4',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.4',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.4',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.8__ql_0.4',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.8__ql_0.4',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.8__ql_0.4',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.4',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.4',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.4',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.4',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_0.8__ql_0.6',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_0.8__ql_0.6',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_0.8__ql_0.6',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.6',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.6',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.6',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.6',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.6',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.8',
 'visit_count__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.8',
 'visit_count__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.8',
 'visit_count__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.8',
 'visit_count__fft_coefficient__attr_"real"__coeff_0',
 'visit_count__fft_coefficient__attr_"real"__coeff_1',
 'visit_count__fft_coefficient__attr_"real"__coeff_2',
 'visit_count__fft_coefficient__attr_"real"__coeff_3',
 'visit_count__fft_coefficient__attr_"real"__coeff_4',
 'visit_count__fft_coefficient__attr_"real"__coeff_5',
 'visit_count__fft_coefficient__attr_"real"__coeff_6',
 'visit_count__fft_coefficient__attr_"real"__coeff_7',
 'visit_count__fft_coefficient__attr_"real"__coeff_8',
 'visit_count__fft_coefficient__attr_"real"__coeff_9',
 'visit_count__fft_coefficient__attr_"real"__coeff_10',
 'visit_count__fft_coefficient__attr_"real"__coeff_11',
 'visit_count__fft_coefficient__attr_"real"__coeff_12',
 'visit_count__fft_coefficient__attr_"real"__coeff_13',
 'visit_count__fft_coefficient__attr_"real"__coeff_14',
 'visit_count__fft_coefficient__attr_"real"__coeff_15',
 'visit_count__fft_coefficient__attr_"real"__coeff_16',
 'visit_count__fft_coefficient__attr_"real"__coeff_17',
 'visit_count__fft_coefficient__attr_"real"__coeff_18',
 'visit_count__fft_coefficient__attr_"real"__coeff_19',
 'visit_count__fft_coefficient__attr_"real"__coeff_20',
 'visit_count__fft_coefficient__attr_"real"__coeff_21',
 'visit_count__fft_coefficient__attr_"real"__coeff_22',
 'visit_count__fft_coefficient__attr_"real"__coeff_23',
 'visit_count__fft_coefficient__attr_"real"__coeff_24',
 'visit_count__fft_coefficient__attr_"real"__coeff_25',
 'visit_count__fft_coefficient__attr_"real"__coeff_26',
 'visit_count__fft_coefficient__attr_"real"__coeff_27',
 'visit_count__fft_coefficient__attr_"real"__coeff_28',
 'visit_count__fft_coefficient__attr_"real"__coeff_29',
 'visit_count__fft_coefficient__attr_"real"__coeff_30',
 'visit_count__fft_coefficient__attr_"real"__coeff_31',
 'visit_count__fft_coefficient__attr_"real"__coeff_32',
 'visit_count__fft_coefficient__attr_"real"__coeff_33',
 'visit_count__fft_coefficient__attr_"real"__coeff_34',
 'visit_count__fft_coefficient__attr_"real"__coeff_35',
 'visit_count__fft_coefficient__attr_"real"__coeff_36',
 'visit_count__fft_coefficient__attr_"real"__coeff_37',
 'visit_count__fft_coefficient__attr_"real"__coeff_38',
 'visit_count__fft_coefficient__attr_"real"__coeff_39',
 'visit_count__fft_coefficient__attr_"real"__coeff_40',
 'visit_count__fft_coefficient__attr_"real"__coeff_41',
 'visit_count__fft_coefficient__attr_"real"__coeff_42',
 'visit_count__fft_coefficient__attr_"real"__coeff_43',
 'visit_count__fft_coefficient__attr_"real"__coeff_44',
 'visit_count__fft_coefficient__attr_"real"__coeff_45',
 'visit_count__fft_coefficient__attr_"real"__coeff_46',
 'visit_count__fft_coefficient__attr_"real"__coeff_47',
 'visit_count__fft_coefficient__attr_"real"__coeff_48',
 'visit_count__fft_coefficient__attr_"real"__coeff_49',
 'visit_count__fft_coefficient__attr_"real"__coeff_50',
 'visit_count__fft_coefficient__attr_"real"__coeff_51',
 'visit_count__fft_coefficient__attr_"real"__coeff_52',
 'visit_count__fft_coefficient__attr_"real"__coeff_53',
 'visit_count__fft_coefficient__attr_"real"__coeff_54',
 'visit_count__fft_coefficient__attr_"real"__coeff_55',
 'visit_count__fft_coefficient__attr_"real"__coeff_56',
 'visit_count__fft_coefficient__attr_"real"__coeff_57',
 'visit_count__fft_coefficient__attr_"real"__coeff_58',
 'visit_count__fft_coefficient__attr_"real"__coeff_59',
 'visit_count__fft_coefficient__attr_"real"__coeff_60',
 'visit_count__fft_coefficient__attr_"real"__coeff_61',
 'visit_count__fft_coefficient__attr_"real"__coeff_62',
 'visit_count__fft_coefficient__attr_"real"__coeff_63',
 'visit_count__fft_coefficient__attr_"real"__coeff_64',
 'visit_count__fft_coefficient__attr_"real"__coeff_65',
 'visit_count__fft_coefficient__attr_"real"__coeff_66',
 'visit_count__fft_coefficient__attr_"real"__coeff_67',
 'visit_count__fft_coefficient__attr_"real"__coeff_68',
 'visit_count__fft_coefficient__attr_"real"__coeff_69',
 'visit_count__fft_coefficient__attr_"real"__coeff_70',
 'visit_count__fft_coefficient__attr_"real"__coeff_71',
 'visit_count__fft_coefficient__attr_"real"__coeff_72',
 'visit_count__fft_coefficient__attr_"real"__coeff_73',
 'visit_count__fft_coefficient__attr_"real"__coeff_74',
 'visit_count__fft_coefficient__attr_"real"__coeff_75',
 'visit_count__fft_coefficient__attr_"real"__coeff_76',
 'visit_count__fft_coefficient__attr_"real"__coeff_77',
 'visit_count__fft_coefficient__attr_"real"__coeff_78',
 'visit_count__fft_coefficient__attr_"real"__coeff_79',
 'visit_count__fft_coefficient__attr_"real"__coeff_80',
 'visit_count__fft_coefficient__attr_"real"__coeff_81',
 'visit_count__fft_coefficient__attr_"real"__coeff_82',
 'visit_count__fft_coefficient__attr_"real"__coeff_83',
 'visit_count__fft_coefficient__attr_"real"__coeff_84',
 'visit_count__fft_coefficient__attr_"real"__coeff_85',
 'visit_count__fft_coefficient__attr_"real"__coeff_86',
 'visit_count__fft_coefficient__attr_"real"__coeff_87',
 'visit_count__fft_coefficient__attr_"real"__coeff_88',
 'visit_count__fft_coefficient__attr_"real"__coeff_89',
 'visit_count__fft_coefficient__attr_"real"__coeff_90',
 'visit_count__fft_coefficient__attr_"real"__coeff_91',
 'visit_count__fft_coefficient__attr_"real"__coeff_92',
 'visit_count__fft_coefficient__attr_"real"__coeff_93',
 'visit_count__fft_coefficient__attr_"real"__coeff_94',
 'visit_count__fft_coefficient__attr_"real"__coeff_95',
 'visit_count__fft_coefficient__attr_"real"__coeff_96',
 'visit_count__fft_coefficient__attr_"real"__coeff_97',
 'visit_count__fft_coefficient__attr_"real"__coeff_98',
 'visit_count__fft_coefficient__attr_"real"__coeff_99',
 'visit_count__fft_coefficient__attr_"imag"__coeff_0',
 'visit_count__fft_coefficient__attr_"imag"__coeff_1',
 'visit_count__fft_coefficient__attr_"imag"__coeff_2',
 'visit_count__fft_coefficient__attr_"imag"__coeff_3',
 'visit_count__fft_coefficient__attr_"imag"__coeff_4',
 'visit_count__fft_coefficient__attr_"imag"__coeff_5',
 'visit_count__fft_coefficient__attr_"imag"__coeff_6',
 'visit_count__fft_coefficient__attr_"imag"__coeff_7',
 'visit_count__fft_coefficient__attr_"imag"__coeff_8',
 'visit_count__fft_coefficient__attr_"imag"__coeff_9',
 'visit_count__fft_coefficient__attr_"imag"__coeff_10',
 'visit_count__fft_coefficient__attr_"imag"__coeff_11',
 'visit_count__fft_coefficient__attr_"imag"__coeff_12',
 'visit_count__fft_coefficient__attr_"imag"__coeff_13',
 'visit_count__fft_coefficient__attr_"imag"__coeff_14',
 'visit_count__fft_coefficient__attr_"imag"__coeff_15',
 'visit_count__fft_coefficient__attr_"imag"__coeff_16',
 'visit_count__fft_coefficient__attr_"imag"__coeff_17',
 'visit_count__fft_coefficient__attr_"imag"__coeff_18',
 'visit_count__fft_coefficient__attr_"imag"__coeff_19',
 'visit_count__fft_coefficient__attr_"imag"__coeff_20',
 'visit_count__fft_coefficient__attr_"imag"__coeff_21',
 'visit_count__fft_coefficient__attr_"imag"__coeff_22',
 'visit_count__fft_coefficient__attr_"imag"__coeff_23',
 'visit_count__fft_coefficient__attr_"imag"__coeff_24',
 'visit_count__fft_coefficient__attr_"imag"__coeff_25',
 'visit_count__fft_coefficient__attr_"imag"__coeff_26',
 'visit_count__fft_coefficient__attr_"imag"__coeff_27',
 'visit_count__fft_coefficient__attr_"imag"__coeff_28',
 'visit_count__fft_coefficient__attr_"imag"__coeff_29',
 'visit_count__fft_coefficient__attr_"imag"__coeff_30',
 'visit_count__fft_coefficient__attr_"imag"__coeff_31',
 'visit_count__fft_coefficient__attr_"imag"__coeff_32',
 'visit_count__fft_coefficient__attr_"imag"__coeff_33',
 'visit_count__fft_coefficient__attr_"imag"__coeff_34',
 'visit_count__fft_coefficient__attr_"imag"__coeff_35',
 'visit_count__fft_coefficient__attr_"imag"__coeff_36',
 'visit_count__fft_coefficient__attr_"imag"__coeff_37',
 'visit_count__fft_coefficient__attr_"imag"__coeff_38',
 'visit_count__fft_coefficient__attr_"imag"__coeff_39',
 'visit_count__fft_coefficient__attr_"imag"__coeff_40',
 'visit_count__fft_coefficient__attr_"imag"__coeff_41',
 'visit_count__fft_coefficient__attr_"imag"__coeff_42',
 'visit_count__fft_coefficient__attr_"imag"__coeff_43',
 'visit_count__fft_coefficient__attr_"imag"__coeff_44',
 'visit_count__fft_coefficient__attr_"imag"__coeff_45',
 'visit_count__fft_coefficient__attr_"imag"__coeff_46',
 'visit_count__fft_coefficient__attr_"imag"__coeff_47',
 'visit_count__fft_coefficient__attr_"imag"__coeff_48',
 'visit_count__fft_coefficient__attr_"imag"__coeff_49',
 'visit_count__fft_coefficient__attr_"imag"__coeff_50',
 'visit_count__fft_coefficient__attr_"imag"__coeff_51',
 'visit_count__fft_coefficient__attr_"imag"__coeff_52',
 'visit_count__fft_coefficient__attr_"imag"__coeff_53',
 'visit_count__fft_coefficient__attr_"imag"__coeff_54',
 'visit_count__fft_coefficient__attr_"imag"__coeff_55',
 'visit_count__fft_coefficient__attr_"imag"__coeff_56',
 'visit_count__fft_coefficient__attr_"imag"__coeff_57',
 'visit_count__fft_coefficient__attr_"imag"__coeff_58',
 'visit_count__fft_coefficient__attr_"imag"__coeff_59',
 'visit_count__fft_coefficient__attr_"imag"__coeff_60',
 'visit_count__fft_coefficient__attr_"imag"__coeff_61',
 'visit_count__fft_coefficient__attr_"imag"__coeff_62',
 'visit_count__fft_coefficient__attr_"imag"__coeff_63',
 'visit_count__fft_coefficient__attr_"imag"__coeff_64',
 'visit_count__fft_coefficient__attr_"imag"__coeff_65',
 'visit_count__fft_coefficient__attr_"imag"__coeff_66',
 'visit_count__fft_coefficient__attr_"imag"__coeff_67',
 'visit_count__fft_coefficient__attr_"imag"__coeff_68',
 'visit_count__fft_coefficient__attr_"imag"__coeff_69',
 'visit_count__fft_coefficient__attr_"imag"__coeff_70',
 'visit_count__fft_coefficient__attr_"imag"__coeff_71',
 'visit_count__fft_coefficient__attr_"imag"__coeff_72',
 'visit_count__fft_coefficient__attr_"imag"__coeff_73',
 'visit_count__fft_coefficient__attr_"imag"__coeff_74',
 'visit_count__fft_coefficient__attr_"imag"__coeff_75',
 'visit_count__fft_coefficient__attr_"imag"__coeff_76',
 'visit_count__fft_coefficient__attr_"imag"__coeff_77',
 'visit_count__fft_coefficient__attr_"imag"__coeff_78',
 'visit_count__fft_coefficient__attr_"imag"__coeff_79',
 'visit_count__fft_coefficient__attr_"imag"__coeff_80',
 'visit_count__fft_coefficient__attr_"imag"__coeff_81',
 'visit_count__fft_coefficient__attr_"imag"__coeff_82',
 'visit_count__fft_coefficient__attr_"imag"__coeff_83',
 'visit_count__fft_coefficient__attr_"imag"__coeff_84',
 'visit_count__fft_coefficient__attr_"imag"__coeff_85',
 'visit_count__fft_coefficient__attr_"imag"__coeff_86',
 'visit_count__fft_coefficient__attr_"imag"__coeff_87',
 'visit_count__fft_coefficient__attr_"imag"__coeff_88',
 'visit_count__fft_coefficient__attr_"imag"__coeff_89',
 'visit_count__fft_coefficient__attr_"imag"__coeff_90',
 'visit_count__fft_coefficient__attr_"imag"__coeff_91',
 'visit_count__fft_coefficient__attr_"imag"__coeff_92',
 'visit_count__fft_coefficient__attr_"imag"__coeff_93',
 'visit_count__fft_coefficient__attr_"imag"__coeff_94',
 'visit_count__fft_coefficient__attr_"imag"__coeff_95',
 'visit_count__fft_coefficient__attr_"imag"__coeff_96',
 'visit_count__fft_coefficient__attr_"imag"__coeff_97',
 'visit_count__fft_coefficient__attr_"imag"__coeff_98',
 'visit_count__fft_coefficient__attr_"imag"__coeff_99',
 'visit_count__fft_coefficient__attr_"abs"__coeff_0',
 'visit_count__fft_coefficient__attr_"abs"__coeff_1',
 'visit_count__fft_coefficient__attr_"abs"__coeff_2',
 'visit_count__fft_coefficient__attr_"abs"__coeff_3',
 'visit_count__fft_coefficient__attr_"abs"__coeff_4',
 'visit_count__fft_coefficient__attr_"abs"__coeff_5',
 'visit_count__fft_coefficient__attr_"abs"__coeff_6',
 'visit_count__fft_coefficient__attr_"abs"__coeff_7',
 'visit_count__fft_coefficient__attr_"abs"__coeff_8',
 'visit_count__fft_coefficient__attr_"abs"__coeff_9',
 'visit_count__fft_coefficient__attr_"abs"__coeff_10',
 'visit_count__fft_coefficient__attr_"abs"__coeff_11',
 'visit_count__fft_coefficient__attr_"abs"__coeff_12',
 'visit_count__fft_coefficient__attr_"abs"__coeff_13',
 'visit_count__fft_coefficient__attr_"abs"__coeff_14',
 'visit_count__fft_coefficient__attr_"abs"__coeff_15',
 'visit_count__fft_coefficient__attr_"abs"__coeff_16',
 'visit_count__fft_coefficient__attr_"abs"__coeff_17',
 'visit_count__fft_coefficient__attr_"abs"__coeff_18',
 'visit_count__fft_coefficient__attr_"abs"__coeff_19',
 'visit_count__fft_coefficient__attr_"abs"__coeff_20',
 'visit_count__fft_coefficient__attr_"abs"__coeff_21',
 'visit_count__fft_coefficient__attr_"abs"__coeff_22',
 'visit_count__fft_coefficient__attr_"abs"__coeff_23',
 'visit_count__fft_coefficient__attr_"abs"__coeff_24',
 'visit_count__fft_coefficient__attr_"abs"__coeff_25',
 'visit_count__fft_coefficient__attr_"abs"__coeff_26',
 'visit_count__fft_coefficient__attr_"abs"__coeff_27',
 'visit_count__fft_coefficient__attr_"abs"__coeff_28',
 'visit_count__fft_coefficient__attr_"abs"__coeff_29',
 'visit_count__fft_coefficient__attr_"abs"__coeff_30',
 'visit_count__fft_coefficient__attr_"abs"__coeff_31',
 'visit_count__fft_coefficient__attr_"abs"__coeff_32',
 'visit_count__fft_coefficient__attr_"abs"__coeff_33',
 'visit_count__fft_coefficient__attr_"abs"__coeff_34',
 'visit_count__fft_coefficient__attr_"abs"__coeff_35',
 'visit_count__fft_coefficient__attr_"abs"__coeff_36',
 'visit_count__fft_coefficient__attr_"abs"__coeff_37',
 'visit_count__fft_coefficient__attr_"abs"__coeff_38',
 'visit_count__fft_coefficient__attr_"abs"__coeff_39',
 'visit_count__fft_coefficient__attr_"abs"__coeff_40',
 'visit_count__fft_coefficient__attr_"abs"__coeff_41',
 'visit_count__fft_coefficient__attr_"abs"__coeff_42',
 'visit_count__fft_coefficient__attr_"abs"__coeff_43',
 'visit_count__fft_coefficient__attr_"abs"__coeff_44',
 'visit_count__fft_coefficient__attr_"abs"__coeff_45',
 'visit_count__fft_coefficient__attr_"abs"__coeff_46',
 'visit_count__fft_coefficient__attr_"abs"__coeff_47',
 'visit_count__fft_coefficient__attr_"abs"__coeff_48',
 'visit_count__fft_coefficient__attr_"abs"__coeff_49',
 'visit_count__fft_coefficient__attr_"abs"__coeff_50',
 'visit_count__fft_coefficient__attr_"abs"__coeff_51',
 'visit_count__fft_coefficient__attr_"abs"__coeff_52',
 'visit_count__fft_coefficient__attr_"abs"__coeff_53',
 'visit_count__fft_coefficient__attr_"abs"__coeff_54',
 'visit_count__fft_coefficient__attr_"abs"__coeff_55',
 'visit_count__fft_coefficient__attr_"abs"__coeff_56',
 'visit_count__fft_coefficient__attr_"abs"__coeff_57',
 'visit_count__fft_coefficient__attr_"abs"__coeff_58',
 'visit_count__fft_coefficient__attr_"abs"__coeff_59',
 'visit_count__fft_coefficient__attr_"abs"__coeff_60',
 'visit_count__fft_coefficient__attr_"abs"__coeff_61',
 'visit_count__fft_coefficient__attr_"abs"__coeff_62',
 'visit_count__fft_coefficient__attr_"abs"__coeff_63',
 'visit_count__fft_coefficient__attr_"abs"__coeff_64',
 'visit_count__fft_coefficient__attr_"abs"__coeff_65',
 'visit_count__fft_coefficient__attr_"abs"__coeff_66',
 'visit_count__fft_coefficient__attr_"abs"__coeff_67',
 'visit_count__fft_coefficient__attr_"abs"__coeff_68',
 'visit_count__fft_coefficient__attr_"abs"__coeff_69',
 'visit_count__fft_coefficient__attr_"abs"__coeff_70',
 'visit_count__fft_coefficient__attr_"abs"__coeff_71',
 'visit_count__fft_coefficient__attr_"abs"__coeff_72',
 'visit_count__fft_coefficient__attr_"abs"__coeff_73',
 'visit_count__fft_coefficient__attr_"abs"__coeff_74',
 'visit_count__fft_coefficient__attr_"abs"__coeff_75',
 'visit_count__fft_coefficient__attr_"abs"__coeff_76',
 'visit_count__fft_coefficient__attr_"abs"__coeff_77',
 'visit_count__fft_coefficient__attr_"abs"__coeff_78',
 'visit_count__fft_coefficient__attr_"abs"__coeff_79',
 'visit_count__fft_coefficient__attr_"abs"__coeff_80',
 'visit_count__fft_coefficient__attr_"abs"__coeff_81',
 'visit_count__fft_coefficient__attr_"abs"__coeff_82',
 'visit_count__fft_coefficient__attr_"abs"__coeff_83',
 'visit_count__fft_coefficient__attr_"abs"__coeff_84',
 'visit_count__fft_coefficient__attr_"abs"__coeff_85',
 'visit_count__fft_coefficient__attr_"abs"__coeff_86',
 'visit_count__fft_coefficient__attr_"abs"__coeff_87',
 'visit_count__fft_coefficient__attr_"abs"__coeff_88',
 'visit_count__fft_coefficient__attr_"abs"__coeff_89',
 'visit_count__fft_coefficient__attr_"abs"__coeff_90',
 'visit_count__fft_coefficient__attr_"abs"__coeff_91',
 'visit_count__fft_coefficient__attr_"abs"__coeff_92',
 'visit_count__fft_coefficient__attr_"abs"__coeff_93',
 'visit_count__fft_coefficient__attr_"abs"__coeff_94',
 'visit_count__fft_coefficient__attr_"abs"__coeff_95',
 'visit_count__fft_coefficient__attr_"abs"__coeff_96',
 'visit_count__fft_coefficient__attr_"abs"__coeff_97',
 'visit_count__fft_coefficient__attr_"abs"__coeff_98',
 'visit_count__fft_coefficient__attr_"abs"__coeff_99',
 'visit_count__fft_coefficient__attr_"angle"__coeff_0',
 'visit_count__fft_coefficient__attr_"angle"__coeff_1',
 'visit_count__fft_coefficient__attr_"angle"__coeff_2',
 'visit_count__fft_coefficient__attr_"angle"__coeff_3',
 'visit_count__fft_coefficient__attr_"angle"__coeff_4',
 'visit_count__fft_coefficient__attr_"angle"__coeff_5',
 'visit_count__fft_coefficient__attr_"angle"__coeff_6',
 'visit_count__fft_coefficient__attr_"angle"__coeff_7',
 'visit_count__fft_coefficient__attr_"angle"__coeff_8',
 'visit_count__fft_coefficient__attr_"angle"__coeff_9',
 'visit_count__fft_coefficient__attr_"angle"__coeff_10',
 'visit_count__fft_coefficient__attr_"angle"__coeff_11',
 'visit_count__fft_coefficient__attr_"angle"__coeff_12',
 'visit_count__fft_coefficient__attr_"angle"__coeff_13',
 'visit_count__fft_coefficient__attr_"angle"__coeff_14',
 'visit_count__fft_coefficient__attr_"angle"__coeff_15',
 'visit_count__fft_coefficient__attr_"angle"__coeff_16',
 'visit_count__fft_coefficient__attr_"angle"__coeff_17',
 'visit_count__fft_coefficient__attr_"angle"__coeff_18',
 'visit_count__fft_coefficient__attr_"angle"__coeff_19',
 'visit_count__fft_coefficient__attr_"angle"__coeff_20',
 'visit_count__fft_coefficient__attr_"angle"__coeff_21',
 'visit_count__fft_coefficient__attr_"angle"__coeff_22',
 'visit_count__fft_coefficient__attr_"angle"__coeff_23',
 'visit_count__fft_coefficient__attr_"angle"__coeff_24',
 'visit_count__fft_coefficient__attr_"angle"__coeff_25',
 'visit_count__fft_coefficient__attr_"angle"__coeff_26',
 'visit_count__fft_coefficient__attr_"angle"__coeff_27',
 'visit_count__fft_coefficient__attr_"angle"__coeff_28',
 'visit_count__fft_coefficient__attr_"angle"__coeff_29',
 'visit_count__fft_coefficient__attr_"angle"__coeff_30',
 'visit_count__fft_coefficient__attr_"angle"__coeff_31',
 'visit_count__fft_coefficient__attr_"angle"__coeff_32',
 'visit_count__fft_coefficient__attr_"angle"__coeff_33',
 'visit_count__fft_coefficient__attr_"angle"__coeff_34',
 'visit_count__fft_coefficient__attr_"angle"__coeff_35',
 'visit_count__fft_coefficient__attr_"angle"__coeff_36',
 'visit_count__fft_coefficient__attr_"angle"__coeff_37',
 'visit_count__fft_coefficient__attr_"angle"__coeff_38',
 'visit_count__fft_coefficient__attr_"angle"__coeff_39',
 'visit_count__fft_coefficient__attr_"angle"__coeff_40',
 'visit_count__fft_coefficient__attr_"angle"__coeff_41',
 'visit_count__fft_coefficient__attr_"angle"__coeff_42',
 'visit_count__fft_coefficient__attr_"angle"__coeff_43',
 'visit_count__fft_coefficient__attr_"angle"__coeff_44',
 'visit_count__fft_coefficient__attr_"angle"__coeff_45',
 'visit_count__fft_coefficient__attr_"angle"__coeff_46',
 'visit_count__fft_coefficient__attr_"angle"__coeff_47',
 'visit_count__fft_coefficient__attr_"angle"__coeff_48',
 'visit_count__fft_coefficient__attr_"angle"__coeff_49',
 'visit_count__fft_coefficient__attr_"angle"__coeff_50',
 'visit_count__fft_coefficient__attr_"angle"__coeff_51',
 'visit_count__fft_coefficient__attr_"angle"__coeff_52',
 'visit_count__fft_coefficient__attr_"angle"__coeff_53',
 'visit_count__fft_coefficient__attr_"angle"__coeff_54',
 'visit_count__fft_coefficient__attr_"angle"__coeff_55',
 'visit_count__fft_coefficient__attr_"angle"__coeff_56',
 'visit_count__fft_coefficient__attr_"angle"__coeff_57',
 'visit_count__fft_coefficient__attr_"angle"__coeff_58',
 'visit_count__fft_coefficient__attr_"angle"__coeff_59',
 'visit_count__fft_coefficient__attr_"angle"__coeff_60',
 'visit_count__fft_coefficient__attr_"angle"__coeff_61',
 'visit_count__fft_coefficient__attr_"angle"__coeff_62',
 'visit_count__fft_coefficient__attr_"angle"__coeff_63',
 'visit_count__fft_coefficient__attr_"angle"__coeff_64',
 'visit_count__fft_coefficient__attr_"angle"__coeff_65',
 'visit_count__fft_coefficient__attr_"angle"__coeff_66',
 'visit_count__fft_coefficient__attr_"angle"__coeff_67',
 'visit_count__fft_coefficient__attr_"angle"__coeff_68',
 'visit_count__fft_coefficient__attr_"angle"__coeff_69',
 'visit_count__fft_coefficient__attr_"angle"__coeff_70',
 'visit_count__fft_coefficient__attr_"angle"__coeff_71',
 'visit_count__fft_coefficient__attr_"angle"__coeff_72',
 'visit_count__fft_coefficient__attr_"angle"__coeff_73',
 'visit_count__fft_coefficient__attr_"angle"__coeff_74',
 'visit_count__fft_coefficient__attr_"angle"__coeff_75',
 'visit_count__fft_coefficient__attr_"angle"__coeff_76',
 'visit_count__fft_coefficient__attr_"angle"__coeff_77',
 'visit_count__fft_coefficient__attr_"angle"__coeff_78',
 'visit_count__fft_coefficient__attr_"angle"__coeff_79',
 'visit_count__fft_coefficient__attr_"angle"__coeff_80',
 'visit_count__fft_coefficient__attr_"angle"__coeff_81',
 'visit_count__fft_coefficient__attr_"angle"__coeff_82',
 'visit_count__fft_coefficient__attr_"angle"__coeff_83',
 'visit_count__fft_coefficient__attr_"angle"__coeff_84',
 'visit_count__fft_coefficient__attr_"angle"__coeff_85',
 'visit_count__fft_coefficient__attr_"angle"__coeff_86',
 'visit_count__fft_coefficient__attr_"angle"__coeff_87',
 'visit_count__fft_coefficient__attr_"angle"__coeff_88',
 'visit_count__fft_coefficient__attr_"angle"__coeff_89',
 'visit_count__fft_coefficient__attr_"angle"__coeff_90',
 'visit_count__fft_coefficient__attr_"angle"__coeff_91',
 'visit_count__fft_coefficient__attr_"angle"__coeff_92',
 'visit_count__fft_coefficient__attr_"angle"__coeff_93',
 'visit_count__fft_coefficient__attr_"angle"__coeff_94',
 'visit_count__fft_coefficient__attr_"angle"__coeff_95',
 'visit_count__fft_coefficient__attr_"angle"__coeff_96',
 'visit_count__fft_coefficient__attr_"angle"__coeff_97',
 'visit_count__fft_coefficient__attr_"angle"__coeff_98',
 'visit_count__fft_coefficient__attr_"angle"__coeff_99',
 'visit_count__fft_aggregated__aggtype_"centroid"',
 'visit_count__fft_aggregated__aggtype_"variance"',
 'visit_count__fft_aggregated__aggtype_"skew"',
 'visit_count__fft_aggregated__aggtype_"kurtosis"',
 'visit_count__value_count__value_0',
 'visit_count__value_count__value_1',
 'visit_count__value_count__value_-1',
 'visit_count__range_count__max_1__min_-1',
 'visit_count__range_count__max_0__min_1000000000000.0',
 'visit_count__range_count__max_1000000000000.0__min_0',
 'visit_count__approximate_entropy__m_2__r_0.1',
 'visit_count__approximate_entropy__m_2__r_0.3',
 'visit_count__approximate_entropy__m_2__r_0.5',
 'visit_count__approximate_entropy__m_2__r_0.7',
 'visit_count__approximate_entropy__m_2__r_0.9',
 'visit_count__friedrich_coefficients__coeff_0__m_3__r_30',
 'visit_count__friedrich_coefficients__coeff_1__m_3__r_30',
 'visit_count__friedrich_coefficients__coeff_2__m_3__r_30',
 'visit_count__friedrich_coefficients__coeff_3__m_3__r_30',
 'visit_count__max_langevin_fixed_point__m_3__r_30',
 'visit_count__linear_trend__attr_"pvalue"',
 'visit_count__linear_trend__attr_"rvalue"',
 'visit_count__linear_trend__attr_"intercept"',
 'visit_count__linear_trend__attr_"slope"',
 'visit_count__linear_trend__attr_"stderr"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"var"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_50__f_agg_"max"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_50__f_agg_"min"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_50__f_agg_"mean"',
 'visit_count__agg_linear_trend__attr_"stderr"__chunk_len_50__f_agg_"var"',
 'visit_count__augmented_dickey_fuller__attr_"teststat"__autolag_"AIC"',
 'visit_count__augmented_dickey_fuller__attr_"pvalue"__autolag_"AIC"',
 'visit_count__augmented_dickey_fuller__attr_"usedlag"__autolag_"AIC"',
 'visit_count__number_crossing_m__m_0',
 'visit_count__number_crossing_m__m_-1',
 'visit_count__number_crossing_m__m_1',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_0',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_1',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_2',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_3',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_4',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_5',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_6',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_7',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_8',
 'visit_count__energy_ratio_by_chunks__num_segments_10__segment_focus_9',
 'visit_count__ratio_beyond_r_sigma__r_0.5',
 'visit_count__ratio_beyond_r_sigma__r_1',
 'visit_count__ratio_beyond_r_sigma__r_1.5',
 'visit_count__ratio_beyond_r_sigma__r_2',
 'visit_count__ratio_beyond_r_sigma__r_2.5',
 'visit_count__ratio_beyond_r_sigma__r_3',
 'visit_count__ratio_beyond_r_sigma__r_5',
 'visit_count__ratio_beyond_r_sigma__r_6',
 'visit_count__ratio_beyond_r_sigma__r_7',
 'visit_count__ratio_beyond_r_sigma__r_10',
 'visit_count__count_above__t_0',
 'visit_count__count_below__t_0',
 'visit_count__lempel_ziv_complexity__bins_2',
 'visit_count__lempel_ziv_complexity__bins_3',
 'visit_count__lempel_ziv_complexity__bins_5',
 'visit_count__lempel_ziv_complexity__bins_10',
 'visit_count__lempel_ziv_complexity__bins_100',
 'visit_count__fourier_entropy__bins_2',
 'visit_count__fourier_entropy__bins_3',
 'visit_count__fourier_entropy__bins_5',
 'visit_count__fourier_entropy__bins_10',
 'visit_count__fourier_entropy__bins_100',
 'visit_count__permutation_entropy__dimension_3__tau_1',
 'visit_count__permutation_entropy__dimension_4__tau_1',
 'visit_count__permutation_entropy__dimension_5__tau_1',
 'visit_count__permutation_entropy__dimension_6__tau_1',
 'visit_count__permutation_entropy__dimension_7__tau_1',
 'visit_count__query_similarity_count__query_None__threshold_0.0',
 'visit_count__matrix_profile__feature_"min"__threshold_0.98',
 'visit_count__matrix_profile__feature_"max"__threshold_0.98',
 'visit_count__matrix_profile__feature_"mean"__threshold_0.98',
 'visit_count__matrix_profile__feature_"median"__threshold_0.98',
 'visit_count__matrix_profile__feature_"25"__threshold_0.98',
 'visit_count__matrix_profile__feature_"75"__threshold_0.98',
 'index']


# In[ ]:





# In[76]:


starttime = timeit.default_timer()
print("The start time is :",starttime)

time = list(range(0, 19))
extraction_settings = ComprehensiveFCParameters()

with open(r'/home/ubuntu/workspace_rohan/data/CO_timeseries_features.csv', 'a') as f:
    writer = csv.writer(f)
    writer.writerow(ts_cols)

    for i, row in data_tseries.iterrows():
        print(i)
        try:
            visit_count = list(row[3:22])

            df = pd.DataFrame({
                'time': time,
                'visit_count': visit_count
            })
            df['id'] = 1

            features = extract_features(df, column_id='id', column_sort='time',
                             default_fc_parameters=extraction_settings,
                             impute_function=impute) 

            features['index'] = i

            row_vals = list((features.values)[0])
            
            writer = csv.writer(f)
            writer.writerow(row_vals)
    
        except:
            pass
        
print("Total training time is :", timeit.default_timer() - starttime)


# In[ ]:




